### ISSUE TITLE
[SHTns] Run-time error : Nlat must be larger than 2*Lmax

### ISSUE THREAD

**Issue by yuchendoudou** [Sebastian-Belkner/cunuSHT#5]
After installing cunusht and related packages, I encountered a run-time error while running the readme code: Nlat must be larger than 2*Lmax. Can you please tell me how to solve this problem? My python environment is 3.10.15 and the installed packages are shown in the image below:
![image](https://github.com/user-attachments/assets/6b9688c1-9b02-4bf5-bee2-9c5f230a0848)

**Comment by nschaeff** [comment]
Hello,
If you upgrade shtns to 3.7.x, it should work

**Comment by yuchendoudou** [comment]
It works, Thank you!
